### ISSUE TITLE
How to get distance map

### ISSUE THREAD

**Issue by lxy2017** [CloudCompare/CloudComPy#167]
nbCpu = psutil.cpu_count()
            bestOctreeLevel = cc.DistanceComputationTools.determineBestOctreeLevel(cloud3, mesh_src)
            params = cc.Cloud2MeshDistancesComputationParams()
            params.maxThreadCount = nbCpu
            params.octreeLevel = bestOctreeLevel
            params.maxSearchDist = 2.0
            cc.DistanceComputationTools.computeCloud2MeshDistances(cloud3, mesh_src, params)

how to get distance map like this 
![image](https://github.com/CloudCompare/CloudComPy/assets/9693098/581f4266-33e2-4915-ad1f-bdf81679916a)

**Comment by prascle** [comment]
Hello,
The `computeCloud2MeshDistances` method creates a new scalar field named `C2M absolute distances` in the cloud.
If you want to create an image by script, see [Rendering a 3D scene to an image file](https://www.simulation.openfields.fr/documentation/CloudComPy/html/userUseCases.html#render-a-3d-scene-to-an-image-file).
Many CloudComPy methods create new scalar fields, but it's not clear in this case : I'll modify the reference documentation and use cases.

Best regards,
Paul

**Comment by lxy2017** [comment]
Thank you for your reply.  I can get the distances map using this code.

sf = mesh2.getAssociatedCloud().getScalarField(mesh2.getAssociatedCloud().getScalarFieldDic()['C2M absolute distances'])
if not mesh2.getAssociatedCloud().hasColors():
    mesh2.getAssociatedCloud().setCurrentScalarField(2)
    mesh2.getAssociatedCloud().convertCurrentScalarFieldToColors()

But I have another problem.  In CloudCampare when I use C2M, change max.distance get diff result.  
![image](https://github.com/CloudCompare/CloudComPy/assets/9693098/7249253c-98f2-4937-a1e4-81a77f8c914d)
![image](https://github.com/CloudCompare/CloudComPy/assets/9693098/178d1780-cef5-48d5-a9bd-93088a5d2a6e)

Using CloudComPy I get same result when I change params.maxSearchDis,   I'm confused as to how I should modify it to get the results I'm looking for.

Thanks again!

**Comment by prascle** [comment]
Hello,
I will try to reproduce this problem. Can you provide a simple dataset and a Python script ?

Best regards,
Paul

**Comment by lxy2017** [comment]
Thanks!  This is test code.  https://drive.google.com/file/d/1sJo4kNGtcLTlIZcwE_dSRnbspKgjMyHR/view?usp=sharing   I got same result like this 
![image](https://github.com/CloudCompare/CloudComPy/assets/9693098/856e6605-a8e8-499a-a0bf-f1cf49722b7c)

**Comment by prascle** [comment]
Hello,
I think the calculation is correct, but, when checking, you're displaying the wrong scalar field: in your screenshot, the scalar field displayed is `Approximate distances`. If you're using CloudCompare to check, select `C2M absolute distances`. See the active scalar field value in the screenshot below.

- If you want to pre-select the correct scalar field in CloudComPy, you need to use the `setCurrentDisplayedScalarField` method: this is useful if you want to render the 3D scene as an image file, or keep the scalar field displayed by default when saving to a bin file.
- In your code, you're trying to convert a scalar field to color, but the `setCurrentScalarField` parameter should be the scalar field number (1 in your case). Converting a scalar field to color is not necessary here.
- There are differences between CloudCompare and CloudComPy: now, by default, CloudCompare calculates signed distances instead of absolute distances, and when you define a maximum distance, the scalar field name is suffixed with the maximum distance, which is not the case with CloudComPy. I'm going to modify CloudComPy to achieve the same behavior as CloudCompare.

Best regards,
Paul

![CloudComPyDistances](https://github.com/CloudCompare/CloudComPy/assets/63641539/252e82a6-7f41-4898-8f46-b4a00fccc49f)

**Comment by lxy2017** [comment]
Thanks again!
