### ISSUE TITLE
Suggestion for adding a new feature: Rasterization using "population to cell" option

### ISSUE THREAD

**Issue by tmoelter** [CloudCompare/CloudComPy#21]
Hi,
I would like to ask for adding a new feature to CloudCompy.
In CloudCompare the rasterization allows to set the raster export options 'Export density (population per cell)'. So far I think this is not implemented in ClouComPy. It would be awesome if this can be added in a future version.
I was looking for other workarounds to obtain the same result but didn't find any simple solution. 

Cheers Tina

**Comment by prascle** [comment]
I implemented something to handle the raster export option 'Export density (population per cell)', after fixing the bugs in issue #20.
The rasterize dialogs are very rich and I have not processed all the options. I have made some choices to handle the raster export options, but since I am not used to using these functions, I would not want to forget or hide a useful option. I am testing with the nice dataset you sent in issue #20.
If you can provide some screenshots of the dialogs as you use them (which selections and options are checked on the rasterize, raster export options... dialogs), I will check that I can reproduce the same choices in Python, before releasing a new version.
Regards,
Paul

**Comment by tmoelter** [comment]
Hi Paul,
that 's awesome. Here are some screenshots of the options I normally use. I think the interpolation option is great, but when I understood the "emptyCellFillStrategy" right this is already implemented. So this should be enough.
![window1](https://user-images.githubusercontent.com/64279750/154012324-e6809dc6-4c09-4d05-8b94-c1315ff421fb.PNG)

The export options "all scalar fields", "heights" and "density" are also often used by myself.

![window2_raster_export_options](https://user-images.githubusercontent.com/64279750/154012327-799337d6-757c-4bb0-98a0-c10a38711a5e.PNG)
 
Regards and thank you very much for your efforts,
Tina

**Comment by prascle** [comment]
It should work with the new release, see https://www.simulation.openfields.fr/
Paul

**Comment by tmoelter** [comment]
Awesome! Thank you very much!
